Repository OvercomingRoom/ULPET-BE, pull requests merged in 2024-06, with the labels that each got.

#3 [Feature] tour api 호출 로직 구현
  document/category_chart.txt
  src/main/java/com/overcomingroom/ulpet/base/BaseEntity.java
  src/main/java/com/overcomingroom/ulpet/base/BaseEntityDateTimeUtil.java
  src/main/java/com/overcomingroom/ulpet/place/domain/Category.java
  src/main/java/com/overcomingroom/ulpet/place/domain/dto/PlaceResponseDto.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/Category.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/Place.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/PlaceImage.java
  src/main/java/com/overcomingroom/ulpet/place/repository/CategoryRepository.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceImageRepository.java
  src/main/java/com/overcomingroom/ulpet/place/service/CategoryService.java
  src/main/java/com/overcomingroom/ulpet/place/service/OpenAPIService.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceDataLoader.java
Labels: ✨ Feature, 🔨 Refactor

#5 :sparkles: feat : 반려동물 동반 정보 api 호출 추가
  src/main/java/com/overcomingroom/ulpet/base/BaseEntityDateTimeUtil.java
  src/main/java/com/overcomingroom/ulpet/place/domain/Category.java
  src/main/java/com/overcomingroom/ulpet/place/service/OpenAPIService.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceDataLoader.java
Labels: ✨ Feature, 🔨 Refactor

#7 [Feature] 스케줄러를 이용한 Api 데이터 갱신 구현
  src/main/java/com/overcomingroom/ulpet/UlpetApplication.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/Place.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/PlaceImage.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceImageRepository.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceRepository.java
  src/main/java/com/overcomingroom/ulpet/place/service/OpenAPIService.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceDataLoader.java
Labels: ✨ Feature

#9 [Feature] 장소 검색 구현
  .gitignore
  build.gradle
  src/main/java/com/overcomingroom/ulpet/config/QueryDslConfig.java
  src/main/java/com/overcomingroom/ulpet/place/controller/PlaceController.java
  src/main/java/com/overcomingroom/ulpet/place/domain/dto/PlaceResponseDto.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/Feature.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/Place.java
  src/main/java/com/overcomingroom/ulpet/place/repository/FeatureRepository.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceRepository.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/overcomingroom/ulpet/place/repository/support/Querydsl4RepositorySupport.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceDataLoader.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceService.java
  src/main/java/com/overcomingroom/ulpet/response/ResponseCode.java
  src/main/resources/application.yml
  src/test/java/com/overcomingroom/ulpet/place/controller/PlaceControllerTest.java
Labels: ✨ Feature, 📬 API

#11 [Feature] 장소 상세 보기
  src/main/java/com/overcomingroom/ulpet/exception/ErrorCode.java
  src/main/java/com/overcomingroom/ulpet/place/controller/PlaceController.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceService.java
  src/test/java/com/overcomingroom/ulpet/place/controller/PlaceControllerTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#13 [Feature] 신규 등록 장소 목록 보기
  src/main/java/com/overcomingroom/ulpet/place/controller/PlaceController.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceRepository.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceService.java
  src/main/java/com/overcomingroom/ulpet/response/ResponseCode.java
  src/test/java/com/overcomingroom/ulpet/place/controller/PlaceControllerTest.java
Labels: ✨ Feature, 📬 API

#15 [Feature] 회원 관련 서비스 및 jwt 인증 구현
  .gitignore
  build.gradle
  src/main/java/com/overcomingroom/ulpet/auth/config/JwtAuthenticationFilter.java
  src/main/java/com/overcomingroom/ulpet/auth/config/JwtExceptionFilter.java
  src/main/java/com/overcomingroom/ulpet/auth/domain/dto/JwtResponseDto.java
  src/main/java/com/overcomingroom/ulpet/auth/service/JwtService.java
  src/main/java/com/overcomingroom/ulpet/base/BaseEntityMember.java
  src/main/java/com/overcomingroom/ulpet/config/EmailConfig.java
  src/main/java/com/overcomingroom/ulpet/config/EncoderConfig.java
  src/main/java/com/overcomingroom/ulpet/config/WebSecurityConfig.java
  src/main/java/com/overcomingroom/ulpet/exception/ErrorCode.java
  src/main/java/com/overcomingroom/ulpet/member/controller/MemberController.java
  src/main/java/com/overcomingroom/ulpet/member/domain/dto/LoginRequestDto.java
  src/main/java/com/overcomingroom/ulpet/member/domain/dto/MemberInfoResponseDto.java
  src/main/java/com/overcomingroom/ulpet/member/domain/dto/SignUpRequestDto.java
  src/main/java/com/overcomingroom/ulpet/member/domain/dto/TempPasswordAndNickname.java
  src/main/java/com/overcomingroom/ulpet/member/domain/dto/UpdateMemberRequestDto.java
  src/main/java/com/overcomingroom/ulpet/member/domain/entity/Member.java
  src/main/java/com/overcomingroom/ulpet/member/domain/entity/MemberEntity.java
  src/main/java/com/overcomingroom/ulpet/member/repository/MemberRepository.java
  src/main/java/com/overcomingroom/ulpet/member/service/MemberService.java
  src/main/java/com/overcomingroom/ulpet/response/ResponseCode.java
  src/main/resources/application-secret.yml.template
Labels: ✨ Feature, 📬 API

#18 [Refactor] 회원가입시 랜덤 닉네임, 프로필 사진 적용
  src/main/java/com/overcomingroom/ulpet/member/domain/dto/SignUpRequestDto.java
  src/main/java/com/overcomingroom/ulpet/member/service/MemberService.java
Labels: 🔨 Refactor

#17 [Feature] 위시리스트 서비스 구현
  src/main/java/com/overcomingroom/ulpet/base/InitData.java
  src/main/java/com/overcomingroom/ulpet/exception/ErrorCode.java
  src/main/java/com/overcomingroom/ulpet/member/controller/WishlistController.java
  src/main/java/com/overcomingroom/ulpet/member/domain/dto/WishlistResponseDto.java
  src/main/java/com/overcomingroom/ulpet/member/domain/entity/MemberEntity.java
  src/main/java/com/overcomingroom/ulpet/member/repository/MemberRepository.java
  src/main/java/com/overcomingroom/ulpet/member/service/WishlistService.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceService.java
  src/main/java/com/overcomingroom/ulpet/response/ResponseCode.java
  src/test/java/com/overcomingroom/ulpet/member/controller/WishlistControllerTest.java
  src/test/java/com/overcomingroom/ulpet/place/service/PlaceServiceTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#20 [fix] 코드 병합으로 인한 문제 수정
  build.gradle
  src/main/java/com/overcomingroom/ulpet/member/domain/entity/MemberEntity.java
Labels: 🐞 BugFix

#22 [Refactor] JWT 구현으로 인한 코드 수정
  src/main/java/com/overcomingroom/ulpet/base/InitData.java
  src/main/java/com/overcomingroom/ulpet/member/controller/MemberController.java
  src/main/java/com/overcomingroom/ulpet/member/controller/WishlistController.java
  src/main/java/com/overcomingroom/ulpet/member/domain/entity/MemberEntity.java
  src/main/java/com/overcomingroom/ulpet/member/repository/MemberRepository.java
  src/main/java/com/overcomingroom/ulpet/member/service/WishlistService.java
  src/test/java/com/overcomingroom/ulpet/member/controller/WishlistControllerTest.java
  src/test/java/com/overcomingroom/ulpet/place/controller/PlaceControllerTest.java
Labels: 🔨 Refactor
