Repository OvercomingRoom/ULPET-BE, pull requests merged in 2024-07, with the labels that each got.

#24 [Feature] 이메일 중복검사 api 생성
  src/main/java/com/overcomingroom/ulpet/base/InitData.java
  src/main/java/com/overcomingroom/ulpet/config/WebSecurityConfig.java
  src/main/java/com/overcomingroom/ulpet/member/controller/MemberController.java
  src/main/java/com/overcomingroom/ulpet/member/service/MemberService.java
  src/main/java/com/overcomingroom/ulpet/response/ResponseCode.java
Labels: ✨ Feature

#25 [Feature] [Fix] 인가된 유저 id 조회 api 생성 및 경위도 수정
  src/main/java/com/overcomingroom/ulpet/member/controller/MemberController.java
  src/main/java/com/overcomingroom/ulpet/member/service/MemberService.java
  src/main/java/com/overcomingroom/ulpet/place/domain/dto/PlaceResponseDto.java
  src/main/java/com/overcomingroom/ulpet/place/service/OpenAPIService.java
  src/main/java/com/overcomingroom/ulpet/response/ResponseCode.java
Labels: 🐞 BugFix, ✨ Feature

#26 [Feature] 사용자 장소 인증 기능
  build.gradle
  src/main/java/com/overcomingroom/ulpet/base/InitData.java
  src/main/java/com/overcomingroom/ulpet/certification/controller/CertificationController.java
  src/main/java/com/overcomingroom/ulpet/certification/domain/dto/CertificationRequestDto.java
  src/main/java/com/overcomingroom/ulpet/certification/domain/dto/CertificationResponseDto.java
  src/main/java/com/overcomingroom/ulpet/certification/domain/entity/Certification.java
  src/main/java/com/overcomingroom/ulpet/certification/repository/CertificationRepository.java
  src/main/java/com/overcomingroom/ulpet/certification/service/CertificationService.java
  src/main/java/com/overcomingroom/ulpet/config/AWSS3Config.java
  src/main/java/com/overcomingroom/ulpet/config/OctetStreamReadMsgConverter.java
  src/main/java/com/overcomingroom/ulpet/config/WebConfig.java
  src/main/java/com/overcomingroom/ulpet/exception/ErrorCode.java
  src/main/java/com/overcomingroom/ulpet/member/service/MemberService.java
  src/main/java/com/overcomingroom/ulpet/member/service/WishlistService.java
  src/main/java/com/overcomingroom/ulpet/place/domain/Category.java
  src/main/java/com/overcomingroom/ulpet/place/domain/dto/PlaceResponseDto.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/Feature.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/Place.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceService.java
  src/main/java/com/overcomingroom/ulpet/response/ResponseCode.java
  src/main/resources/application.yml
  src/test/java/com/overcomingroom/ulpet/place/controller/PlaceControllerTest.java
Labels: ✨ Feature, 📬 API

#28 [Feature] 인증 수에 따른 검색 정렬
  src/main/java/com/overcomingroom/ulpet/place/controller/PlaceController.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceService.java
Labels: ✨ Feature

#32 [Refactor] 회원 탈퇴 코드 수정 (비밀 번호 검증 로직 추가)
  src/main/java/com/overcomingroom/ulpet/member/controller/MemberController.java
  src/main/java/com/overcomingroom/ulpet/member/service/MemberService.java
Labels: 🔨 Refactor

#34 [Refactor] 연관 클래스 생성
  src/main/java/com/overcomingroom/ulpet/certification/domain/dto/CertificationResponseDto.java
  src/main/java/com/overcomingroom/ulpet/certification/domain/entity/Certification.java
  src/main/java/com/overcomingroom/ulpet/certification/domain/entity/CertificationFeature.java
  src/main/java/com/overcomingroom/ulpet/certification/repository/CertificationFeatureRepository.java
  src/main/java/com/overcomingroom/ulpet/certification/service/CertificationService.java
  src/main/java/com/overcomingroom/ulpet/exception/ErrorCode.java
  src/main/java/com/overcomingroom/ulpet/member/domain/entity/MemberEntity.java
  src/main/java/com/overcomingroom/ulpet/member/domain/entity/Wishlist.java
  src/main/java/com/overcomingroom/ulpet/member/repository/WishlistRepository.java
  src/main/java/com/overcomingroom/ulpet/member/service/WishlistService.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/Feature.java
  src/main/java/com/overcomingroom/ulpet/place/domain/entity/Place.java
  src/main/java/com/overcomingroom/ulpet/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/overcomingroom/ulpet/place/service/PlaceService.java
  src/test/java/com/overcomingroom/ulpet/member/controller/WishlistControllerTest.java
  src/test/java/com/overcomingroom/ulpet/place/service/PlaceServiceTest.java
Labels: 🔨 Refactor, ✅ Test
